### ISSUE TITLE
Unhandled exception error when adding or editing games in desktop app

### ISSUE THREAD

**Issue by Chelle55** [Project-Eris-psc/Project-Eris-Issue-Tracker#18]
I didn't used to have this issue when I used the desktop app in the past but now, every time I try to add a game or edit game details I get the error below thrown.

I'm on Windows 10 whereas I was on Windows 7 before, I thought it might be the new usb I'm using but it does it with the old one I used to use where it worked fine.
I'm using the desktop app version 1.0.0.673

Any help greatly appreciated!

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at projectErisUI.FrmGameManager.btEditGameIni_Click(Object sender, EventArgs e) in D:\DEV\Repos\project-eris-desktop-ui\projectErisUI\FrmGameManager.cs:line 2158
   at projectErisUI.FrmGameManager.btNewFolder_Click(Object sender, EventArgs e) in D:\DEV\Repos\project-eris-desktop-ui\projectErisUI\FrmGameManager.cs:line 1999
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at DarkUI.Controls.DarkButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
projectErisUI
    Assembly Version: 1.0.0.673
    Win32 Version: 1.0.0.673
    CodeBase: file:///C:/Users/Chelle/Desktop/Eris/projectErisUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
DarkUI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Chelle/Desktop/Eris/DarkUI.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.112.1
    Win32 Version: 1.0.112.1
    CodeBase: file:///C:/Users/Chelle/Desktop/Eris/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4584.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by Chelle55** [comment]
It seems to happen randomly and I'm somehow able to use the program now, doesn't happen anywhere near as much. Weird.

**Comment by eku** [comment]
```System.Net.WebException: The operation has timed out at System.Net.HttpWebRequest.GetResponse()```

Check your internet connection.

**Comment by ThisIsSet-L** [comment]
I'm having the same issue when using this app. Tested on Windows 10 and in WINE. Both environments have full gigabit internet access.
It would be helpful to know *what* domain/page it is accessing to determine if it's a routing or website issue.

**Comment by ThisIsSet-L** [comment]
I think it may be cdn.thegamesdb.com from my Wireshark capture. I'm able to reach the page normally. Not sure what's up, but it's very consistently throwing.

**Comment by ThisIsSet-L** [comment]
Disabling IPv6 in the system has resolved this issue for me. I have no issue with any other IPv6-based websites, and could see SYN/ACK from the cdn.thegamesdb.com AAAA address, so not entirely sure what's going on.

**Comment by ThisIsSet-L** [comment]
Issue appears occasionally on IPv4. Could it be some form of anti-scraping from Cloudflare or API rate-limiting?
